//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vGameRecommender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vGameRecommender.GameResource", typeof(GameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which platform would you preferred?.
        /// </summary>
        internal static string AIOrSinglePersonQuestion {
            get {
                return ResourceManager.GetString("AIOrSinglePersonQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to pay for your games?.
        /// </summary>
        internal static string BudgetQuestion {
            get {
                return ResourceManager.GetString("BudgetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whom would you like to control?.
        /// </summary>
        internal static string ControlQuestion {
            get {
                return ResourceManager.GetString("ControlQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are the games recommend based on your previous preference:.
        /// </summary>
        internal static string FinalRecommend {
            get {
                return ResourceManager.GetString("FinalRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which part would you prefer to focus on?.
        /// </summary>
        internal static string FocusOnQuestion {
            get {
                return ResourceManager.GetString("FocusOnQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of games would you like to play most?.
        /// </summary>
        internal static string GoalQuestion {
            get {
                return ResourceManager.GetString("GoalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of below would you prefer?.
        /// </summary>
        internal static string MechanicQuestion {
            get {
                return ResourceManager.GetString("MechanicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whom you wish to play with?.
        /// </summary>
        internal static string OpponentQuestion {
            get {
                return ResourceManager.GetString("OpponentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of below pace would you prefer?.
        /// </summary>
        internal static string PaceQuestion {
            get {
                return ResourceManager.GetString("PaceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play with someone else?.
        /// </summary>
        internal static string PartnerQuestion {
            get {
                return ResourceManager.GetString("PartnerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of below perspective would you prefer?.
        /// </summary>
        internal static string PerspectiveQuestion {
            get {
                return ResourceManager.GetString("PerspectiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of below skills you would like to learn?.
        /// </summary>
        internal static string SkillQuestion {
            get {
                return ResourceManager.GetString("SkillQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which kind of opponents you wish to play?.
        /// </summary>
        internal static string SocialTypeQuestion {
            get {
                return ResourceManager.GetString("SocialTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Video Game Recommender System!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
